def PIPELINE_NAME = "issuer-web"

def LIB_NAME= "covid19-es-lib"
def LIB_REPO = "https://github.com/bcgov/essential-services-delivery.git"
def LIB_BRANCH = "master"
library identifier: "${LIB_NAME}@${LIB_BRANCH}", 
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${LIB_REPO}",
          branches: [[name: "*/${LIB_BRANCH}"]]])  

node {

  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"

  stage("Build ${config.BASE_IMAGE_NAME} ...") {
    script {
      openshift.withCluster() {
        openshift.withProject() {
          echo "Building the base image ..."
          build(openshift, 
                "${config.BASE_IMAGE_NAME}",
                config.WAIT_TIMEOUT)
        }
      }
    }
  }

  stage("Build ${config.RUNTIME_IMAGE_NAME} ...") {
    script {
      openshift.withCluster() {
        openshift.withProject() {
          echo "Building the base image ..."
          build(openshift, 
                "${config.RUNTIME_IMAGE_NAME}",
                config.WAIT_TIMEOUT)
        }
      }
    }
  }

  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }
}